server:
  port: 8084
spring:
  application:
    name: app1
kfcregistry:
  serverlist:
    - http://localhost:8084
    - http://localhost:8085
    - http://localhost:8086
logging:
  level:
    root: info
    io.github.tomcatlab: debug
