### 获取所有服务实例
GET http://localhost:8084/fetchAll?service = com.cola.kfcrpc.demo.api.UserService

### 注册一个实例
POST http://localhost:8086/reg?service=com.cola.kfcrpc.demo.api.UserService
Content-Type: application/json

{
  "context": "kfcrpc",
  "host": "127.0.0.1",
  "port": 8080,
  "scheme": "http",
  "status": false,
  "parameters": {
    "env": "dev",
    "tag": "RED"
  }
}


### 取消注册一个实例
POST http://localhost:8084/unreg?service= com.cola.kfcrpc.demo.api.UserService
Content-Type: application/json

{
  "context": "kfcrpc",
  "host": "127.0.0.1",
  "port": 8081,
  "scheme": "http"
}

### 设置leader
GET http://localhost:8084/setLeader

### get version
GET http://localhost:8084/version?service= com.cola.kfcrpc.demo.api.UserService

### info
GET http://localhost:8084/info
### cluster
GET http://localhost:8086/cluster
### info 85
GET http://localhost:8485/info
### cluster 85
GET http://localhost:8485/cluster
### sl 85
GET http://localhost:8485/sl

### snapshot 8484
GET http://localhost:8484/snapshot